package dr.mtr.passenger.enums;

public enum TripStatus {


    TAXI_NOT_AVAILABLE,
    RIDER_ENTERING_DETAILS_AND_NOT_PRESSED_DONE,
    RIDER_ENTERED_DETAILS_AND_NOT_PRESSED_RIDE_NOW,
    RIDER_ENTERED_DETAILS_AND_PRESSED_TO_RIDE,
    RIDER_CONFIRMED_TRIP_SEARCHING_NEARBY_TAXI,
    NEARBY_TAXI_FOUND_DRIVER_COMING_TOWARDS_RIDER,
    RIDER_PICKED_UP_TRIP_STARTED,
    TRIP_COMPLTED_DROPED_OFF,
    DRIVER_ARRIVED_WAITING_FOR_CUSTOMER,
    NO_SHOW;


}
